MODEL:
  TYPE: mobilenet
  NUM_CLASSES: 1000
  ACTIVATION_FUN: relu6
MNV2:
  STEM_W: 32
  DEPTHS: [1, 1, 1, 1, 2, 1, 3, 1, 2, 1, 2, 1] # n
  WIDTHS: [16, 24, 24, 32, 32, 64, 64, 96, 96, 160, 160, 320] # c
  EXP_SIZES: [32, 96, 144, 144, 192, 192, 384, 384, 576, 576, 960, 960] # t
  STRIDES: [1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1] # s
  KERNELS: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  NONLINEARITY: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  SQUEEZE_AND_EXCITE: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  HEAD_W: 1280
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2 #
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  #WARMUP_EPOCHS: 5 #
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256 #
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200 #
NUM_GPUS: 2
OUT_DIR: .
